### ISSUE TITLE
Unable to install qsym using virtual environment

### ISSUE THREAD

**Issue by qsphan** [sslab-gatech/qsym#10]
Hi,

I'm trying to install `qsym` using the virtual environment, but it seems I cannot compile `pin`. The message error was 

> This kit requires gcc 3.4 or later

While I have gcc 6.3. I'm attaching the full message

[virtualError.txt](https://github.com/sslab-gatech/qsym/files/2333887/virtualError.txt)

I cannot install with Docker either, but it might be due to some problems with the proxy, I will try again in another machine. I think it would be useful if you have an image in Docker Hub.

Best,
Sang

**Comment by jakkdu** [comment]
Hi, Sang.
Yes. Currently, QSYM has some dependency in compiler.
I think using ubuntu 16.04 or ubuntu 14.04 would be better way to work with QSYM.
Thanks.

**Comment by qsphan** [comment]
@jakkdu I see, but is it possible to build a docker image and put it in Docker Hub?

**Comment by jakkdu** [comment]
True. But currently PIN, DBT used by QSYM, also has kernel dependency.
You can refer #4. So even though we provide docker image, it will not work in some kernel.
