### ISSUE TITLE
the experiment on the CGC dataset

### ISSUE THREAD

**Issue by MaggieCwj** [sslab-gatech/qsym#109]
Hello, I want to know how you conducted the experiment on the CGC dataset? We tried to reproduce this experiment on ubuntu16.04, but failed to compile the CGC program successfully. I would be very grateful if I could get your answer.

**Comment by insuyun** [comment]
Hi, Maggie. Hope this helps: https://github.com/sslab-gatech/qsym/issues/54#issuecomment-561763185.

**Comment by MaggieCwj** [comment]
> Hi, Maggie. Hope this helps: [#54 (comment)](https://github.com/sslab-gatech/qsym/issues/54#issuecomment-561763185).

Thank you for your help! yesterday i compiled the CGC programs in this repository:
![image](https://user-images.githubusercontent.com/33512054/218674663-6f8290ec-06b2-4c00-9136-37a5078e3ec1.png)

and i fuzz it like this:
afl: `afl-fuzz -S afl-qsym -i pov/ -o bcfuzz/out1 -- ./The_Longest_Road-afl`
qsym: `/home/maggie/qsym/bin/run_qsym_afl.py -a afl-qsym -o bcfuzz/out1 -n qsym -- ./The_Longest_Road`

However, qsym didn't generate any testcase. 
Is these commands wrong?

**Comment by insuyun** [comment]
Hi, Let me check what's going on.

**Comment by insuyun** [comment]
Hi. Sorry for late reply.
cb-multios is not working with qsym. This is because pin's error, not qsym.
(even I failed to run it with a simple pintool with a instruction counter).
So I recommend you to use libcgc-x86 to compile cgc binaries.
