### ISSUE TITLE
Run test failed with pintool load error

### ISSUE THREAD

**Issue by natalie13m** [sslab-gatech/qsym#11]
Hi guys! I had some problems with the tool. I installed everything as told in README.md. When I run
`python -m pytest -n $(nproc)`
I got a lot of errors. An example is as below.

>  ___________________________________ test_dup ___________________________________
[gw0] linux2 -- Python 2.7.12 /home/natalie/Research/qsym/venv/bin/python
    def test_dup():
        testcases = get_all_testcases("dup")
        # default + 0xdeadbeef
       assert len(testcases) == 2
E       AssertionError: assert 1 == 2
E        +  where 1 = len(['\x00\x00\x00\x00\n'])
test_schedule.py:79: AssertionError
------------------------------ Captured log call -------------------------------
executor.py                 92 DEBUG    Executing /home/natalie/Research/qsym/venv/lib/python2.7/site-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /home/natalie/Research/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/qsym-sf0C_q/qsym-out-0/pin.log -i /tmp/qsym-B8Vz_X -s 1 -o /tmp/qsym-sf0C_q/qsym-out-0 -b /tmp/qsym-hLzZtC -- /home/natalie/Research/qsym/tests/schedule/dup/main
========================== 249 failed in 2.82 seconds ==========================

Also, I got this in the pin.log file.

> Pin 2.14 kit 71293
E:  Unable to load /home/natalie/Research/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so: /home/natalie/Research/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so: undefined symbol: _ZN4llvm24DisableABIBreakingChecksE

I have no idea about where this symbol comes from.

Another question about this tool: can I use it to fuzz 64-bit binaries? I saw your TODO file and it says it is going to support both 32bit and 64bit. But for now, is it compatible with 64bit binaries?

I am now using a Ubuntu 14.04 64bit machine.

**Comment by jakkdu** [comment]
It seems like there is some conflict in llvm version.
I have no idea exact reason since it is the first error that I see.
Could you use Dockerfile to install it?

Currently, QSYM only supports 64bit binary.
32bit can be supported by changing some compiler flags.

**Comment by natalie13m** [comment]
Problem solved with Dockerfile installation. Thanks a lot!
