### ISSUE TITLE
question about DARPA CGC dataset

### ISSUE THREAD

**Issue by orangeloong** [sslab-gatech/qsym#110]
Hello, qsym's paper says that when you test the cgc programs , you ignore 5 programs that need IPC. Can you tell me the names of these 5 programs? I would appreciate it if you could answer my question.
![image](https://user-images.githubusercontent.com/49509727/219275806-70ed30fc-cb30-44e4-b651-a50c996eaba7.png)

**Comment by insuyun** [comment]
Hi. They are challenges with multiple binaries.
So I believe they are the followings.
```txt
$ find . -name cb_1|sort
./KPRCA_00016/cb_1
./KPRCA_00024/cb_1
./KPRCA_00048/cb_1
./NRFIN_00006/cb_1
./YAN01_00009/cb_1
```

**Comment by orangeloong** [comment]
> Hi. They are challenges with multiple binaries. So I believe they are the followings.
> 
> ```
> $ find . -name cb_1|sort
> ./KPRCA_00016/cb_1
> ./KPRCA_00024/cb_1
> ./KPRCA_00048/cb_1
> ./NRFIN_00006/cb_1
> ./YAN01_00009/cb_1
> ```
Your response was so fast, thank you very much！！！
