### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by evanmak** [sslab-gatech/qsym#13]
Hi,

I am trying to setup qsym but encountered test failures. The pin.log shows

"Unable to load /qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so: /qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so: undefined symbol: _ZN4llvm5APInt12initSlowCaseEmb"

could you please provide some suggestions on how to resolve this?

**Comment by jakkdu** [comment]
Could you check whether you are using  different version for llvm lib?
We are using  the default one from Ubuntu package manager. 
It seems it cannot find the llvm library.

**Comment by evanmak** [comment]
Right, i updated my clang and llvm version to the latest ones. After installing with the docker file I am able to run it. Thanks.
