### ISSUE TITLE
why this old Pin?

### ISSUE THREAD

**Issue by vanhauser-thc** [sslab-gatech/qsym#14]
This might be not the right place to ask this - why Pin? and why such a very old version that is not suited for modern kernels and x64?

DynamoRio is about 10x faster, but yes, it takes longer to code the same functionality.

**Comment by jakkdu** [comment]
This is because I couldn't find a good DBT that supports libz3.
I tried DynamoRIO, too. But failed. 
I also wanted to use other DBT, not old PIN, but had no choice when I started to develop this.

https://github.com/sslab-gatech/qsym/issues/4#issuecomment-414696829

**Comment by jakkdu** [comment]
If we have anything to discuss more, maybe we can discuss in #4.
