### ISSUE TITLE
incorrect parsing of solving time

### ISSUE THREAD

**Issue by jhu066** [sslab-gatech/qsym#17]
In the file of <executor.py>. The solving time is not correctly parsed from the log file because of the wrong initialization of `LOG_SMT_HEADER` . As a result, the solving time is always 0 because the branch of 
`if l.startswith(LOG_SMT_HEADER):` is never entered. 

This is how the pin.log file looks like in my case:
![image](https://user-images.githubusercontent.com/34012578/45970953-aff42400-bfec-11e8-8ab5-c0cfd6df2295.png)

There's blank in the beginning of each line, so it should be:
`LOG_SMT_HEADER = " [STAT] SMT:" // there's a blank in the beginning` 
instead of:
`LOG_SMT_HEADER = "[STAT] SMT:" // without the blank`

**Comment by jakkdu** [comment]
Thanks.
