### ISSUE TITLE
Question about #AFL_CMDLINE

### ISSUE THREAD

**Issue by stevenagy** [sslab-gatech/qsym#18]
Hello,

I noticed this line in the environment variables:
`#   AFL_CMDLINE: command line for a testing program for AFL (ASAN + instrumented)`

Is using an ASAN explicitly required? 

Also, what instrumentation is required? I'm guessing by this you mean afl-cc, but I'm also wondering if AFL-Dyninst and AFL-QEMU are supported?

Thanks,
-Stefan

**Comment by jakkdu** [comment]
Hi,  Stefan.
ASAN is optional.
I haven't test AFL-Dyninst, but AFL-QEMU would work. 

Thanks,
- Insu Yun

**Comment by stevenagy** [comment]
Got it, thanks!

With regards to running QSYM:
```
# run AFL master
$ $(AFL_ROOT)/afl-fuzz -M afl-master -i $(INPUT) -o $(OUTPUT) -- $(AFL_CMDLINE)
# run AFL slave
$ $(AFL_ROOT)/afl-fuzz -S afl-slave -i $(INPUT) -o $(OUTPUT) -- $(AFL_CMDLINE)
# run QSYM
$ bin/run_qsym_afl.py -a afl-slave -o $(OUTPUT) -n qsym -- $(QSYM_CMDLINE)
```

Is it necessary to run AFL in both master _and_ slave mode? Or just master mode? My intuition is that QSYM is running as a slave with respect to AFL being master.

Thanks!

**Comment by jakkdu** [comment]
No, you don't have to.
But I suggest you to run `at least one slave mode` AFL.
Because if your input is too long, deterministic mode takes too much time to finish. 
In that case, QSYM cannot get any input from AFL, and it will be stuck because of AFL.
That's why I use two AFL instances.

**Comment by stevenagy** [comment]
I see. I find it interesting that the Steelix project found only 1 instance of AFL (master) was necessary. 

Did you notice significant disparities in coverage between slave/no-slave configurations? Specifically, whereas your evals showed that `QSYM + AFL master + AFL slave` successfully beat `AFL master + 2xAFL slave`... did `QSYM + AFL master` beat `AFL master + AFL slave`?

**Comment by jakkdu** [comment]
If AFL master stucks, `QSYM + AFL master` will not beat `AFL master + AFL slave` since QSYM will be stuck, too. If you want to use a single AFL instance, then I suggest you to use AFL slave, instead of AFL master.

**Comment by jakkdu** [comment]
Yes.

**Comment by stevenagy** [comment]
Awesome. Thank you so much!
