### ISSUE TITLE
All tests fail

### ISSUE THREAD

**Issue by benlaurie** [sslab-gatech/qsym#2]
If I run the tests, there are 249 tests and 249 failures. For example:

```
target = '/usr/local/google/home/benl/git-work/qsym/tests/syscall/mremap'

    def test_syscall(target):
>       assert run_single_test(target)
E       AssertionError: assert False
E        +  where False = run_single_test('/usr/local/google/home/benl/git-work/qsym/tests/syscall/mremap')

test_syscall.py:19: AssertionError
```

**Comment by mxmssh** [comment]
There is file called pin.log in the test folder, could you please print it out here. I had the same issue.

**Comment by jakkdu** [comment]
I think this would be the problem of ptrace_scope. Please check new README or pin.log that @mxmssh mentioned.

**Comment by jakkdu** [comment]
Thanks.
I just pushed c538ebd2453d07a0bf8cca551f73361b4bcbdb04 that fixes documentation to use pip instead of  `python setup.py install`.
This will build libqsym.so.

**Comment by BinLeeBit** [comment]
When I run tests, there are "E: Unable to load /../qsym/qsym/pintool/obj-intel64/libqsym.so" in **pin.log.** I just use `python setup.py build` instead of `python setup.py install` in **README.md.** It can run, but slowly.

**Comment by jakkdu** [comment]
@BinLeeBit 
I think you are looking at old README.md.
I changed it to use `pip install .` instead of `python setup.py install`.
Then it will work. (I hope)
You can use `python setup.py build` and `python setup.py install` to install this project, too.
Sorry for confusion.

**Comment by jakkdu** [comment]
This issue is also same with #4.
