### ISSUE TITLE
Question about #QSYM_CMDLINE

### ISSUE THREAD

**Issue by mbryantramirez** [sslab-gatech/qsym#22]
Hello,

I had a question about the environment variable 
`QSYM_CMDLINE: command line for a testing program for QSYM (Naive)`

I understand that this means I will need to pass a program that will not be instrumented but I'm having some difficulties visualizing this I tried an input that looked something like this 

 `$bin/run_qsym_afl.py -a afl-slave -o bin/output/ -n qsym ./binutils/readelf`

where the program is readelf of the binutils program but this error is thrown 

`Traceback (most recent call last):
File "bin/run_qsym_afl.py", line 17, in <module> 
import qsym 
ImportError: No module named qsym`

Thank you.

**Comment by jakkdu** [comment]
Hi,
Have you install the qsym?
You need to install the qsym before run this.

**Comment by mbryantramirez** [comment]
I've followed the installation instructions up to this point when im in virtualenv I see that pip has qsym installed so im not sure why qsym is not being recognized as a module

**Comment by jakkdu** [comment]
@mbryantramirez I came up with a possible problem while scanning the issues.
Did you check your python? Currently, we use python2, not python3.
(Forgive me that I used old LTS for old PIN).

**Comment by CK213** [comment]
Hi, I am having a similar problem. Except I made sure I am using python2 by typing the following command `alias python=python2` so my python --version is Python 2.7.12.
I realised that my pytest version is 2.8.2, when I tried to upgrade it into the latest version, error occurs.
`ERROR: Could not find a version that satisfies the requirement pytest==6.0.2`.

**Comment by insuyun** [comment]
Please re-open it if you need any more help.
