### ISSUE TITLE
Trouble in using QSYM to find test inputs on some simple toy example

### ISSUE THREAD

**Issue by jchoi2022** [sslab-gatech/qsym#24]
Hi, thank you for the great work and making it open source.

I'm having a trouble while testing QSYM on some simple toy program.

I wrote a simple toy program that reads in 8 byte input from file and compare it to magic value. Running it with input "DCBAabcd" will raise a segfault as follow.
```
jason@debian-8:~/example$ cat test.c 
#include <unistd.h>
#include <fcntl.h>
#include <stdint.h>

int main(int argc, char** argv)
{
  char buf[9];
  int fd;

  fd = open(argv[1], O_RDONLY);
  read(fd, buf, sizeof(buf) - 1);
  buf[8] = 0;

  if (*(int32_t*) &buf[0] == 0x41424344) {
    if(buf[4] == 'a') {
        *(int*) NULL = 0;
    }
  }
  return 0;
}
jason@debian-8:~/example$ gcc test.c  -o test.bin
jason@debian-8:~/example$ echo "DCBAabcd" > file
jason@debian-8:~/example$ ./test.bin file
Segmentation fault
```
When I tested QSYM on this program, it seems to fail in finding a test input that penetrates the branch condition. I followed the instructions in README to run one AFL master, one AFL slave and one QSYM. I provided 8 bytes of "A" as initial dummy seed of AFL. The standard output of QSYM looks as follow.
```
...
(venv)jason@debian-8:~/example$ export QSYM_CMDLINE="/home/jason/example/test.bin /home/jason/example/file_qsym"
(venv)jason@debian-8:~/example$ /home/jason/qsym/bin/run_qsym_afl.py -f /home/jason/example/file_qsym -a afl-slave -o $OUTPUT -n qsym -- $QSYM_CMDLINE
DEBUG:qsym.afl:Temp directory=/tmp/tmpluyS8E
DEBUG:qsym.afl:Run qsym: input=/home/jason/example/output/afl-slave/queue/id:000000,orig:empty
DEBUG:qsym.Executor:Executing timeout -k 5 90 /home/jason/qsym/venv/lib/python2.7/site-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /home/jason/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/tmpluyS8E/qsym-out-0/pin.log -i /home/jason/example/file_qsym -s 1 -o /tmp/tmpluyS8E/qsym-out-0 -l 1 -b /home/jason/example/output/qsym/bitmap -- /home/jason/example/test.bin /home/jason/example/file_qsym
DEBUG:qsym.afl:Total=4 s, Emulation=4 s, Solver=0 s, Return=0
DEBUG:qsym.afl:Generate 0 testcases
DEBUG:qsym.afl:0 testcases are new
DEBUG:qsym.afl:Sleep for getting files
DEBUG:qsym.afl:Sleep for getting files
...
```

The content of input file to QSYM was 4 bytes of 'A', and I think concolic execution should be able to find a new test input "DCBA" that can flip the first `if` branch.

```
jason@debian-8:~/example$ xxd output/afl-master/queue/id\:000000\,orig\:empty 
0000000: 4141 4141                                AAAA
```

Could you take a look at this problem, or point out my mistakes if I'm making some?

I am using debian 8.11 OS, but its kernel version is same to Ubuntu 14.04, and the build succeeded without any error.  

Thank you.

**Comment by jakkdu** [comment]
Could you give me your AFL command, too?
Also, QSYM currently doesn't have an option equivalent to `-f` in AFL.

**Comment by jchoi2022** [comment]
To run AFL master node, I used the following bash script.
```
#!/bin/bash
export AFL_ROOT="/workdir/afl-2.52b"
export INPUT="/workdir/example/input"
export OUTPUT="/workdir/example/output"
export AFL_CMDLINE="/workdir/example/test.bin @@"
$AFL_ROOT/afl-fuzz -Q -M afl-master -i $INPUT -o $OUTPUT -- $AFL_CMDLINE
```
And for AFL slave node, I used this script.
```
#!/bin/bash
export AFL_ROOT="/workdir/afl-2.52b"
export INPUT="/workdir/example/input"
export OUTPUT="/workdir/example/output"
export AFL_CMDLINE="/workdir/example/test.bin @@"
$AFL_ROOT/afl-fuzz -Q -S afl-slave -i $INPUT -o $OUTPUT -- $AFL_CMDLINE
```
And for QSYM, I used this one.
```
export AFL_ROOT="/workdir/afl-2.52b"
export INPUT="/workdir/example/input"
export OUTPUT="/workdir/example/output"
export QSYM_CMDLINE="/workdir/example/test.bin @@"
/workdir/qsym/bin/run_qsym_afl.py -a afl-slave -o $OUTPUT -n qsym -- $QSYM_CMDLINE
```

**Comment by jakkdu** [comment]
Oh, I think the problem is about `-Q`.
Currently, QSYM cannot support `-Q` option. 
I think I should fix this issue.
Please refer: https://github.com/sslab-gatech/qsym/issues/19

**Comment by jakkdu** [comment]
Could you check the latest version?
I added option for QEMU.
The toy example works for my side.

**Comment by jchoi2022** [comment]
Hi, I just checked the latest version, and it works well in my environment as well. Thank you for the fix!
