### ISSUE TITLE
Question about enabling optimistic solving

### ISSUE THREAD

**Issue by tianxiaogu** [sslab-gatech/qsym#26]
Thanks for releasing qsym. This project is really awesome.

We recently tried to run qsym on LAVA but we do not know how to turn on/off the optimistic solving. When running qsym with the default options, we obtained results that are more like those without optimistic solving  (Fig. 11 in the paper of USENIX Security).

Our settings:
Ubuntu 16.04, 64bit,
Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz, 16 GB memory
afl 2.52b, one master and one slave.

**Comment by jakkdu** [comment]
Hi, First thank you for your testing.
Currently, optimistic solving is turned on as default in QSYM.
I think there is something wrong with your QSYM.
Could you tell me how you run QSYM and current results in LAVA?
Please check whether there are testcases in `qsym/queue`.
Thank you!

**Comment by jakkdu** [comment]
If I understand correctly, I think you used instrumented binaries for AFL and QSYM.
Could you use uninstrumented binaries for QSYM?

**Comment by tianxiaogu** [comment]
Thanks a lot, @jakkdu , I checked that the binaries for QSYM are uninstrumented and built by native clang 8 with the default optimization level. The problem may be caused by the compiler and the compiler flags. Will let you known once I have figured it out.

**Comment by jakkdu** [comment]
Could you check `*-optimistic` in qsym/queue?
It should be there if optimistic solving is turned on. 

Thank you!

**Comment by tianxiaogu** [comment]
Thanks, @jakkdu , there are no `*-optimistic` in `qsym/queue`. I probably need to reinstall the qsym and review the installation log.

**Comment by jakkdu** [comment]
Sorry, I found I made a mistake. `*-optimistic` cannot be found `qsym/queue`, but only QSYM's log.

**Comment by insuyun** [comment]
Please re-open it if you need any more help.
