### ISSUE TITLE
Setup questions

### ISSUE THREAD

**Issue by Elothis** [sslab-gatech/qsym#28]
Hello,
I am currently trying to get QSYM to work and am facing a few questions regarding the setup, with which you can maybe help me out:

1. Do the inputs AFL_CMDLINE and QSYM_CMDLINE have to be paths to a binary (QEMU mode AFL) or just the source code of the target program I want to fuzz?
2. I guess AFL_CMDLINE and QSYM_CMDLINE have to point to the same program for it to make any sense, right? So AFL_CMDLINE would point to an instrumented target (compiled with afl-cc) and QSYM_CMDLINE to the **same program** but compiled normally? (or completely uncompiled? does qsym compile it itself?)
3. How exactly would I go about running it via Docker? When builiding a container via the provided Dockerfile, there is no AFL installed inside this container and I cannot access an AFL installation outside of the container from within. Would I have to add to the Dockerfile to also install AFL inside the container, so I can follow the instructions under "Run hybrid fuzzing with AFL" in your ReadMe?
4. What exactly do the commands listed under your point "Run for testing" in your ReadMe do? Is that just to test if QSYM was installed correctly or is this actually another way of fuzzing a target without the hybrid method with AFL master+slave explained in the chapter above that in your ReadMe?

I am trying to understand how everything works, so I apologize for all the questions, but I would be very glad if you could help me.

Thanks a lot and best wishes!

**Comment by jakkdu** [comment]
Hi!

1. paths to a binary + its option. For example, `objdump -D @@`. QSYM uses same semantics with AFL's one.
2. Yes. Same programs. But AFL needs instrumented one and QSYM needs uninstrumented one.
3. You need to install AFL manually. The setup script does not include AFL installation.
4. To test if QSYM was installed correctly.

Thanks!
Best,
Insu Yun.

**Comment by Elothis** [comment]
Hey,
thanks for the quick response!

So just to further clarify if I understand everything correctly:
I take the source code of the target I want to fuzz, compile it one time with afl-cc for the instrumentation and set the path to that binary falling out of the compilation with afl-cc to AFL_CMDLINE. Additionally, I compile the target program normally (with standard gcc) and set that binary to QSYM_CMDLINE.
Correct?

Thanks!

**Comment by jakkdu** [comment]
Yes!

**Comment by Elothis** [comment]
Alright, sounds good!

One last question which has more to do with my mind trying to understand the docker thing I guess:
When running QSYM via a docker container built by your provided Dockerfile, how do you go about running it in conjunction with the AFL installation? As I understand it, running QSYM inside the container like described here via `$ docker run --cap-add=SYS_PTRACE -it qsym /bin/bash` starts an isolated, encapsulated QSYM instance that cannot share the INPUT and OUTPUT directories with AFL. So I guess I would have to either add an AFL intallation to the Dockerfile to have it inside the same container as well, or - when having AFL installed locally on my machine - to map volumes from inside the QSYM container to outside on my local machine to share the INPUT and OUTPUT directories so AFL can run locally on my machine and QSYM via the docker container, correct?

**Comment by jakkdu** [comment]
Yes. I think either way would work since QSYM and AFL communicate through files. 
Thanks.

**Comment by Elothis** [comment]
Alright, thank you very much for your help!

Cheers!

**Comment by Elothis** [comment]
Alright, this was the option I considered as most applicable anyways, thanks!
