### ISSUE TITLE
Output/Findings

### ISSUE THREAD

**Issue by Elothis** [sslab-gatech/qsym#31]
Hello there!

I have a small question about how QSYM puts out its new findings:
Does it just make us of the afl folder structure and adds inputs to the crashes/ directory that procuded crashes or does it have some sort of extra output format?

Thanks!

**Comment by jakkdu** [comment]
Hi!
QSYM uses AFL's sync mechanism to communicate with QSYM. File contents are inputs of a program and file names should start with `id: + 6 digit integers`.

**Comment by Elothis** [comment]
So that means, that QSYM adds these files to the existing AFL folder structure in the same way AFL does, so I can also use AFLs tools to analyze, minimize or plot the results of AFL+QSYM afterwards?

**Comment by jakkdu** [comment]
I guess so. But I am not sure how afl tools work.

**Comment by Elothis** [comment]
Alright, but if its just files with contents that procude crashes in the same folder as AFL puts these (/crashes/) it will work just the same.

Thanks a lot!
