### ISSUE TITLE
Cannot find any bugs in LAVA

### ISSUE THREAD

**Issue by maverick117** [sslab-gatech/qsym#33]
Hi, thanks for open sourcing your work. 

I've been testing QSYM on the LAVA-M `who` dataset, and it appears that QSYM cannot find any bugs. I'm using two AFL instances and a QSYM instance as listed in the README. The `queue` directory under the QSYM output directory is empty, and all the input files under `errors` and `hangs` can run without crashing or hanging.

Any idea where I might have made a mistake?

**Comment by jakkdu** [comment]
Hi. It seems QSYM does not work.
Could you check your command line again?

**Comment by maverick117** [comment]
I've been running QSYM in a docker container.

On host machine:
```
$ docker run --cap-add=SYS_PTRACE -it qsym /bin/bash
```

In qsym container:
```
$ afl-fuzz -M master -i input -o output -- ./who.afl @@
$ afl-fuzz -S slave -i input -o output -- ./who.afl @@
$ python qsym/bin/run_qsym_afl.py -a slave -o output -n qsym -- who.plain @@
```

The log indicates that there have been 0 new inputs in every iteration.

Another issue I found was that QSYM would report an index out of range exception:
```
Traceback (most recent call last):
  File "qsym/bin/run_qsym_afl.py", line 47, in <module>
    main()
  File "qsym/bin/run_qsym_afl.py", line 41, in main
    e.run()
  File "/usr/local/lib/python2.7/dist-packages/qsym/afl.py", line 356, in run
    self.run_file(fp)
  File "/usr/local/lib/python2.7/dist-packages/qsym/afl.py", line 376, in run_file
    if not self.minimizer.check_testcase(testcase):
  File "/usr/local/lib/python2.7/dist-packages/qsym/minimizer.py", line 68, in check_testcase
    return self.is_interesting_testcase(this_bitmap, proc.returncode)
  File "/usr/local/lib/python2.7/dist-packages/qsym/minimizer.py", line 81, in is_interesting_testcase
    old = my_bitmap[i]
IndexError: list index out of range
```

**Comment by maverick117** [comment]
Okay, I solved the problem by recompiling AFL. Thanks for the help!
