### ISSUE TITLE
Doubt about use

### ISSUE THREAD

**Issue by caballomaldito** [sslab-gatech/qsym#34]
In the documentation i can see the following guide:

# run AFL master
$ $(AFL_ROOT)/afl-fuzz -M afl-master -i $(INPUT) -o $(OUTPUT) -- $(AFL_CMDLINE)
# run AFL slave
$ $(AFL_ROOT)/afl-fuzz -S afl-slave -i $(INPUT) -o $(OUTPUT) -- $(AFL_CMDLINE)
# run QSYM
$ bin/run_qsym_afl.py -a afl-slave -o $(OUTPUT) -n qsym -- $(QSYM_CMDLINE)

However, i have several questions:

1. Can i create a 50 AFL slaves and later run 1 slave of QSYM?, or i need create 50 AFL slaves and 50 QSYM slaves?, example

$(AFL_ROOT)/afl-fuzz -S afl-slave1 -i $(INPUT) -o $(OUTPUT) -- $(AFL_CMDLINE)
$(AFL_ROOT)/afl-fuzz -S afl-slave2 -i $(INPUT) -o $(OUTPUT) -- $(AFL_CMDLINE)
$(AFL_ROOT)/afl-fuzz -S afl-slave3 -i $(INPUT) -o $(OUTPUT) -- $(AFL_CMDLINE)
...
bin/run_qsym_afl.py -a afl-slave1 -o $(OUTPUT) -n qsym -- $(QSYM_CMDLINE)
bin/run_qsym_afl.py -a afl-slave2 -o $(OUTPUT) -n qsym -- $(QSYM_CMDLINE)
bin/run_qsym_afl.py -a afl-slave3 -o $(OUTPUT) -n qsym -- $(QSYM_CMDLINE)
...

2. the name of QSYM "afl-slave" should match with the "afl-slave" name of alf-fuzz? or is irrelevant?, example

$(AFL_ROOT)/afl-fuzz -S afl-slave1 -i $(INPUT) -o $(OUTPUT) -- $(AFL_CMDLINE)
bin/run_qsym_afl.py -a afl-slaveNOTMATCH999 -o $(OUTPUT) -n qsym -- $(QSYM_CMDLINE)

Thanks!

**Comment by jakkdu** [comment]
Hi,
1. You can create 50 AFL with 1 QSYM.
2. The name should be match.  The slave name indicates where QSYM gets your AFL inputs.

**Comment by caballomaldito** [comment]
Hi,

> * You can create 50 AFL with 1 QSYM.

Ok, however, I understand that I will have more fastest results if I use more slaves QSYM, or not?

Thanks!

**Comment by jakkdu** [comment]
I don't think so.
Currently, we don't support synchronization among QSYM instances.
Thus, QSYM instances will perform independently and cannot benefit from multiple instances.

**Comment by caballomaldito** [comment]
Ok, thanks!
