### ISSUE TITLE
Compile error (Unable to build pintool)

### ISSUE THREAD

**Issue by caballomaldito** [sslab-gatech/qsym#35]
Tested  on SO: Ubuntu 18.04 TLS

#error The C++ ABI of your compiler does not match the ABI of the pin kit.
      ^~~~~
    /tmp/pip-req-build-QqjGha/third_party/pin-2.14-71313-gcc.4.4.7-linux/source/include/pin/compiler_version_check2.H:117:2: error: #error This kit requires gcc 3.4 or later
     #error This kit requires gcc 3.4 or later
      ^~~~~
    /tmp/pip-req-build-QqjGha/third_party/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Config/makefile.default.rules:170: recipe for target 'obj-intel64/allocation.o' failed
    make: *** [obj-intel64/allocation.o] Error 1
    make: *** Waiting for unfinished jobs....
    /tmp/pip-req-build-QqjGha/third_party/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Config/makefile.default.rules:170: recipe for target 'obj-intel64/call_stack_manager.o' failed
    make: *** [obj-intel64/call_stack_manager.o] Error 1
    /tmp/pip-req-build-QqjGha/third_party/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Config/makefile.default.rules:170: recipe for target 'obj-intel64/afl_trace_map.o' failed
    make: *** [obj-intel64/afl_trace_map.o] Error 1
    /tmp/pip-req-build-QqjGha/third_party/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Config/makefile.default.rules:170: recipe for target 'obj-intel64/analysis_instruction.o' failed
    make: *** [obj-intel64/analysis_instruction.o] Error 1
    /tmp/pip-req-build-QqjGha/third_party/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Config/makefile.default.rules:170: recipe for target 'obj-intel64/analysis.o' failed
    make: *** [obj-intel64/analysis.o] Error 1
    make: Leaving directory '/tmp/pip-req-build-QqjGha/qsym/pintool'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-QqjGha/setup.py", line 54, in <module>
        data_files=data_files
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/peto/qsym/venv/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-QqjGha/setup.py", line 29, in run
        self.execute(build_pintool, (), msg='Building pintool')
      File "/usr/lib/python2.7/distutils/cmd.py", line 349, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/lib/python2.7/distutils/util.py", line 309, in execute
        func(*args)
      File "/tmp/pip-req-build-QqjGha/setup.py", line 18, in build_pintool
        raise ValueError("Unable to build pintool")
    ValueError: Unable to build pintool
    
    ----------------------------------------
Command "/home/peto/qsym/venv/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-QqjGha/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-gr2RlI/install-record.txt --single-version-externally-managed --compile --install-headers /home/peto/qsym/venv/include/site/python2.7/qsym" failed with error code 1 in /tmp/pip-req-build-QqjGha/

**Comment by jakkdu** [comment]
This problem is caused by old pin that QSYM uses.
I suggest you to use 16.04 or 14.04, which has been tested.
Please check #4 for further information.
Sorry for your inconvenience!

**Comment by wcventure** [comment]
@jakkdu 

Hi, jakkdu.
I tested on Ubuntu 14.04 TLS, but also get this problem.
I used docker to install QSYM but fail.
```
$ echo 0|sudo tee /proc/sys/kernel/yama/ptrace_scope
$ ./setup.sh
$ sudo docker build -t qsym ./
```

I get the follow errors.
```
    In file included from logging.cpp:6:0:
    solver.h:4:18: fatal error: z3++.h: No such file or directory
    compilation terminated.
    /tmp/pip-pNMFms-build/third_party/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Config/makefile.default.rules:170: recipe for target 'obj-intel64/logging.o' failed
    make: *** [obj-intel64/logging.o] Error 1
    make: *** Waiting for unfinished jobs....
    In file included from analysis_instruction.h:6:0,
                     from analysis_instruction.cpp:2:
    expr.h:12:18: fatal error: z3++.h: No such file or directory
    compilation terminated.
    In file included from analysis_instruction.h:6:0,
                     from analysis.cpp:3:
    expr.h:12:18: fatal error: z3++.h: No such file or directory
    compilation terminated.
    /tmp/pip-pNMFms-build/third_party/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Config/makefile.default.rules:170: recipe for target 'obj-intel64/analysis.o' failed
    make: *** [obj-intel64/analysis.o] Error 1
    /tmp/pip-pNMFms-build/third_party/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Config/makefile.default.rules:170: recipe for target 'obj-intel64/analysis_instruction.o' failed
    make: *** [obj-intel64/analysis_instruction.o] Error 1
    In file included from expr_cache.h:4:0,
                     from expr_cache.cpp:1:
    expr.h:12:18: fatal error: z3++.h: No such file or directory
    compilation terminated.
    In file included from expr_cache.h:4:0,
                     from expr_builder.h:6,
                     from expr_evaluate.cpp:1:
    expr.h:12:18: fatal error: z3++.h: No such file or directory
    compilation terminated.
    /tmp/pip-pNMFms-build/third_party/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Config/makefile.default.rules:170: recipe for target 'obj-intel64/expr_cache.o' failed
    make: *** [obj-intel64/expr_cache.o] Error 1
    /tmp/pip-pNMFms-build/third_party/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Config/makefile.default.rules:170: recipe for target 'obj-intel64/expr_evaluate.o' failed
    make: *** [obj-intel64/expr_evaluate.o] Error 1
    In file included from main.cpp:12:0:
    solver.h:4:18: fatal error: z3++.h: No such file or directory
    compilation terminated.
    /tmp/pip-pNMFms-build/third_party/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Config/makefile.default.rules:170: recipe for target 'obj-intel64/main.o' failed
    make: *** [obj-intel64/main.o] Error 1
    In file included from expr_cache.h:4:0,
                     from expr_builder.h:6,
                     from memory.h:10,
                     from flags.h:5,
                     from flags.cpp:1:
    expr.h:12:18: fatal error: z3++.h: No such file or directory
    compilation terminated.
    In file included from expr_cache.h:4:0,
                     from expr_builder.h:6,
                     from memory.h:10,
                     from flags.h:5,
                     from thread_context.h:7,
                     from instrument.cpp:2:
    expr.h:12:18: fatal error: z3++.h: No such file or directory
    compilation terminated.
    /tmp/pip-pNMFms-build/third_party/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Config/makefile.default.rules:170: recipe for target 'obj-intel64/flags.o' failed
    make: *** [obj-intel64/flags.o] Error 1
    /tmp/pip-pNMFms-build/third_party/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Config/makefile.default.rules:170: recipe for target 'obj-intel64/instrument.o' failed
    make: *** [obj-intel64/instrument.o] Error 1
    rm expr__gen.cpp expr_builder__gen.cpp
    make: Leaving directory '/tmp/pip-pNMFms-build/qsym/pintool'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-pNMFms-build/setup.py", line 54, in <module>
        data_files=data_files
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-pNMFms-build/setup.py", line 29, in run
        self.execute(build_pintool, (), msg='Building pintool')
      File "/usr/lib/python2.7/distutils/cmd.py", line 349, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/lib/python2.7/distutils/util.py", line 309, in execute
        func(*args)
      File "/tmp/pip-pNMFms-build/setup.py", line 18, in build_pintool
        raise ValueError("Unable to build pintool")
    ValueError: Unable to build pintool

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-pNMFms-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-d5vnqE-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-pNMFms-build/
```

**Comment by jakkdu** [comment]
It seems like there z3 was not installed properly.
Could you check log for z3 installation?

**Comment by insuyun** [comment]
Please re-open it if you need any more help.
