### ISSUE TITLE
pin.log

### ISSUE THREAD

**Issue by BinLeeBit** [sslab-gatech/qsym#38]
The file _pin.log_
Pin 2.14kit 71293
E:  Unable to load /home/kj/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so: /home/kj/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so:
undefined symbol:Z3_is_seq_sort

Thank you!

**Comment by ashgeek** [comment]
How did you fix this?
