### ISSUE TITLE
Current release not queueing test cases 

### ISSUE THREAD

**Issue by stevenagy** [sslab-gatech/qsym#40]
Hey all,

I'm having some trouble with the current release of QSYM when running in hybrid mode with AFL. It doesn't appear that any generated test cases are getting queued. I'm setting up QSYM to run with QEMU mode tracing (I set qemu_mode to be True by default in minimizer.py) and using a differently-instrumented binary (e.g., Dyninst) for the AFL component. The /out_dir/qsym/queue/ directory is empty even after 24hrs of fuzzing. Any ideas?

Thanks,
-Stefan

**Comment by stevenagy** [comment]
Nevermind, I think I fixed it!

**Comment by jakkdu** [comment]
Sounds good. 
Sorry, I was busy with my personal issue.
