### ISSUE TITLE
bin/run_qsym_afl.py  ERROR

### ISSUE THREAD

**Issue by Fayozbek** [sslab-gatech/qsym#41]
The first of all thank you for perfect work.
I install QSYM successfully by the following README and I install AFL 2.52b as well.
However, when I run QSYM_CMDLINE `bin/run_qsym_afl.py -a afl-slave -o output/ -n qsym -- ./home/bek/Desktop/qsym/uniq`  I get ERROR `IOError: [Errno 2] No such file or directory: 'output/afl-slave/fuzzer_stats`

`(venv) bek@ubuntu:~/Desktop/qsym$bin/run_qsym_afl.py -a afl-slave -o output/ -n qsym -- ./home/bek/Desktop/qsym/uniq
Traceback (most recent call last):
  File "bin/run_qsym_afl.py", line 47, in <module>
    main()
  File "bin/run_qsym_afl.py", line 39, in main
    args.name, args.filename, args.mail, args.asan_bin)
  File "/home/bek/Desktop/qsym/venv/local/lib/python2.7/site-packages/qsym/afl.py", line 130, in __init__
    cmd, afl_path, qemu_mode = self.parse_fuzzer_stats()
  File "/home/bek/Desktop/qsym/venv/local/lib/python2.7/site-packages/qsym/afl.py", line 197, in parse_fuzzer_stats
    cmd = get_afl_cmd(os.path.join(self.afl_dir, "fuzzer_stats"))
  File "/home/bek/Desktop/qsym/venv/local/lib/python2.7/site-packages/qsym/afl.py", line 65, in get_afl_cmd
    with open(fuzzer_stats) as f:
IOError: [Errno 2] No such file or directory: 'output/afl-slave/fuzzer_stats'`
Even I create folder "afl-slave -> fuzzer_stats" There is an error anyway!
I am a beginner in software testing area, maybe I wrote something wrong.
Any advice will be appreciated.

**Comment by Fayozbek** [comment]
2. After running `bin/run_qsym_afl.py -a afl-slave -o ./output/ -n qsym -- ./bignum`
`DEBUG:qsym.afl:Temp directory=/tmp/tmptlUIZy
DEBUG:qsym.afl:Run qsym: input=./output/afl-slave/queue/id:000003,orig:test4.txt
DEBUG:qsym.Executor:Executing timeout -k 5 90 /home/bek/Desktop/qsym/venv/lib/python2.7/site-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /home/bek/Desktop/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/tmptlUIZy/qsym-out-0/pin.log -i /home/bek/Desktop/qsym/output/qsym/.cur_input -s 1 -o /tmp/tmptlUIZy/qsym-out-0 -l 1 -b ./output/qsym/bitmap -- ./bignum
DEBUG:qsym.afl:Total=2 s, Emulation=2 s, Solver=0 s, Return=127
DEBUG:qsym.afl:Generate 0 testcases
DEBUG:qsym.afl:0 testcases are new
DEBUG:qsym.afl:Crash is found: ./output/afl-slave/crashes/id:000000,sig:11,src:000001,op:havoc,rep:128
DEBUG:qsym.afl:Crash is found: ./output/afl-master/crashes/id:000000,sig:11,src:000002,op:havoc,rep:128
DEBUG:qsym.afl:Crash is found: ./output/afl-master/crashes/id:000001,sig:11,src:000003,op:havoc,rep:64
DEBUG:qsym.afl:Run qsym: input=./output/afl-slave/queue/id:000002,orig:test3.txt
DEBUG:qsym.Executor:Executing timeout -k 5 90 /home/bek/Desktop/qsym/venv/lib/python2.7/site-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /home/bek/Desktop/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/tmptlUIZy/qsym-out-1/pin.log -i /home/bek/Desktop/qsym/output/qsym/.cur_input -s 1 -o /tmp/tmptlUIZy/qsym-out-1 -l 1 -b ./output/qsym/bitmap -- ./bignum
DEBUG:qsym.afl:Total=2 s, Emulation=2 s, Solver=0 s, Return=127
DEBUG:qsym.afl:Generate 0 testcases
DEBUG:qsym.afl:0 testcases are new
DEBUG:qsym.afl:Run qsym: input=./output/afl-slave/queue/id:000000,orig:test1.txt
DEBUG:qsym.Executor:Executing timeout -k 5 90 /home/bek/Desktop/qsym/venv/lib/python2.7/site-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh -ifeellucky -t /home/bek/Desktop/qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so -logfile /tmp/tmptlUIZy/qsym-out-3/pin.log -i /home/bek/Desktop/qsym/output/qsym/.cur_input -s 1 -o /tmp/tmptlUIZy/qsym-out-3 -l 1 -b ./output/qsym/bitmap -- ./bignum
DEBUG:qsym.afl:Total=2 s, Emulation=2 s, Solver=0 s, Return=127
DEBUG:qsym.afl:Generate 0 testcases
DEBUG:qsym.afl:0 testcases are new
DEBUG:qsym.afl:Sleep for getting files
DEBUG:qsym.afl:Sleep for getting files
DEBUG:qsym.afl:Sleep for getting files
DEBUG:qsym.afl:Sleep for getting files
DEBUG:qsym.afl:Sleep for getting files
DEBUG:qsym.afl:Sleep for getting files
DEBUG:qsym.afl:Sleep for getting files
DEBUG:qsym.afl:Sleep for getting files
DEBUG:qsym.afl:Sleep for getting files
DEBUG:qsym.afl:Sleep for getting files`

What is the meaning of `DEBUG:qsym.afl:Sleep for getting files`?
It means i am runnig QSYM in right way?

**Comment by jakkdu** [comment]
Hi,
First, you should run AFL before running QSYM to get inputs from AFL.
The error about `fuzzer_stats` is about this.

Second, if you run qsym for long time, `Sleep for getting files` is natural.  It means that both AFL and QSYM cannot find new inputs and are stuck. But if it is so urgent like your case, it means it has some error. Could you check your AFL work well? i.e., can find some new inputs?
