### ISSUE TITLE
Return code 247 from qsym

### ISSUE THREAD

**Issue by davidp-due** [sslab-gatech/qsym#46]
I am trying to run qsym in a docker container.
However, when i check the output of qsym I only get a lot of:
`DEBUG:qsym.afl:Total=0 s, Emulation=0 s, Solver=0 s, Return=247`
`DEBUG:qsym.afl:Generate 0 testcases`
`DEBUG:qsym.afl:0 testcases are new`

All output dirs of qsym are empty.
Afl seems to run fine (e.g., it finds crashes). Any idea on what I am be doing wrong?

**Comment by jakkdu** [comment]
Hi, David.
You can check a PIN command that QSYM runs.
This would help you to find a problem.

Thanks.

**Comment by jakkdu** [comment]
@davidp-due could you share what was the problem?

**Comment by davidp-due** [comment]
The problem was actually not related to qsym.
