### ISSUE TITLE
docker build failed

### ISSUE THREAD

**Issue by cponcelets** [sslab-gatech/qsym#48]
Hello qsym community and thank you for your nice work.
I recently wanted to run qsym using the docker image but get several errors while building it.

Mainly:

```
efile:4112: recipe for target 'z3' failed
/workdir/qsym/third_party/z3 /workdir/qsym



small_object_allocator.cpp:(.text+0xc53): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, int)'
small_object_allocator.cpp:(.text+0xc6e): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, int)'
util/util.a(small_object_allocator.o):small_object_allocator.cpp:(.text+0xcb1): more undefined references to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, int)' follow
collect2: error: ld returned 1 exit status
make: *** [z3] Error 1
```
,
```
Collecting pytest>=4.4.0 (from pytest-xdist->qsym===0.1)
  Downloading https://files.pythonhosted.org/packages/3a/3b/f839b8431582e0f4e5f98230300db70b795f467503b2cdb0bf7eb9b18351/pytest-5.2.1.tar.gz (971kB)
  Running setup.py (path:/tmp/pip-build-F1lVhE/pytest/setup.py) egg_info for package pytest produced metadata for project name unknown. Fix your #egg=pytest fragments.
```
and
```
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-jbTM4_-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0fhZeV-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-jbTM4_-build/
You are using pip version 8.1.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
I am on ubuntu16.04.

Am i missing something?
Best.

**Comment by jakkdu** [comment]
Hi. Sorry for late reply.
Now I have time to check this. 
I think you installed QSYM in your local machine and use Docker later.
Because of that, I think the z3 object files for 32bit are remained in the folder, resulting in that error.
I update the installation script to clean the build directory when you install (https://github.com/sslab-gatech/qsym/commit/7c77d8a6c5186190a88cf03d51350afcaf9a068a).
Please use the latest version and let me know if you still have the problem.

Thank you.

Best,
Insu Yun.

**Comment by cponcelets** [comment]
Hi, no problem, thank you for your answer.
I see, I expected Docker to be isolated.

I managed to install qsym on my local machine,
it is good if you specify that old-gcc and python2 are required.
For example with: `virtualenv -p python2 venv` in the makefile/setup.sh.

Now, the tests are running, which means that every qsym's features are working?
They lasted 277 seconds.
I ask because I cannot get the LAVA-M speed and saw that it may come from the optimistic solving.
Is there a way to check if it is working? I do not see optimistic* input as specified in #26.

**Comment by jakkdu** [comment]
Actually, Docker is isolated, but I think you run `setup.sh` in your host machine once.

Could you show me your command line for LAVA-M?
I want to check whether you run it correctly.

**Comment by cponcelets** [comment]
Of course, I only tried for the uniq example, there is my process.

I first use the script to compile the two binaries (instrumented for afl and not) called `uniq-afl` and `uniq`, then I run on three terms:

1)  afl-fuzz -M afl-master -i input -o output -- uniq-afl
2) afl-fuzz -S afl-slave -i input -o output -- uniq-afl
3) python run_qsym_afl.py -a afl-slave -o output -n qsym -- uniq

With alf-fuzz from afl-2.52b and after activating venv for 3).
The process seems working, (no red for afl) and I have test cases generated by qsym.
The input is the good seed man-clag3-sorted.

However, no optimistic* in qsym queue only some `id:0000--,src:id:--` files.
You have found bugs after few seconds if I understood well the paper, haven't you?

**Comment by jakkdu** [comment]
Could you check our [VM](https://github.com/sslab-gatech/qsym/tree/master/vagrant)?

**Comment by insuyun** [comment]
Please re-open it if you need any more help.
