### ISSUE TITLE
Illegal instruction when running Imagemagick

### ISSUE THREAD

**Issue by BrieflyX** [sslab-gatech/qsym#49]
Hello, I tried QSYM using ImageMagick in Docker environment with an ubuntu 16.04 server.
However, when it analyzes `magick` binary, the pin program crashes.
Debugging shows it seems to generate a `xbegin` instruction which is not supported on my server.
Dry run without instrumentation is fine. Do you have any idea about this issue?
Here is some log

```
......
[INFO] fixed mapping via mmap(2) at 0x7f9c4f082000
[INFO] IMG: /usr/lib/x86_64-linux-gnu/libfreetype.so.6
[INFO] IMG: /lib/x86_64-linux-gnu/libpng12.so.0
[INFO] IMG: /usr/lib/x86_64-linux-gnu/libfontconfig.so.1
[INFO] IMG: /usr/lib/x86_64-linux-gnu/libxml2.so.2
[INFO] IMG: /lib/x86_64-linux-gnu/libz.so.1
[INFO] IMG: /usr/lib/x86_64-linux-gnu/libgomp.so.1
[INFO] IMG: /lib/x86_64-linux-gnu/libm.so.6
[INFO] IMG: /lib/x86_64-linux-gnu/libgcc_s.so.1
[INFO] IMG: /lib/x86_64-linux-gnu/libpthread.so.0
[INFO] IMG: /lib/x86_64-linux-gnu/libc.so.6
[INFO] IMG: /lib/x86_64-linux-gnu/libexpat.so.1
[INFO] IMG: /lib/x86_64-linux-gnu/libdl.so.2
[INFO] IMG: /usr/lib/x86_64-linux-gnu/libicuuc.so.55
[INFO] IMG: /lib/x86_64-linux-gnu/liblzma.so.5
[INFO] IMG: /usr/lib/x86_64-linux-gnu/libicudata.so.55
[INFO] IMG: /usr/lib/x86_64-linux-gnu/libstdc++.so.6
C: Tool (or Pin) caused signal 4 at PC 0x7f9cbc669d00
C: Location may be in in-lined analysis code, try re-running with '-inline 0' to debug it[1]    10316 illegal hardware instruction -ifeellucky -t  -logfile /tmp/tmpPVaJv1/qsym-out-0/pin.log -i
```

**Comment by jakkdu** [comment]
Hi, it seems that magick incorrectly check your cpu information.
Could you make this [analysisCpuId](https://github.com/sslab-gatech/qsym/blob/e67839e74a8d6960efb735d6e7dfdb58d634f2a0/qsym/pintool/analysis_instruction.cpp#L862) function empty?

Originally, this is used for disabling optimizations to make analysis easier in symbolic execution,
but it could make a problem in your case because of modifying your CPUID.

Thank you.

**Comment by BrieflyX** [comment]
OK, it seems `cpuid` stuff does affect program execution. After commenting related codes and disabling analyzing code for `xsave`, `xrstore`, now it has worked.

Thank you for help!
