### ISSUE TITLE
ASAN support

### ISSUE THREAD

**Issue by mxmssh** [sslab-gatech/qsym#5]
Hi guys,

Thank you for amazing project. Does QSYM support AFL with ASAN mode ?

I tried it for one open-source project and it worked pretty good without ASAN but when I compile my target with Address Sanitizer, QSYM reports "0 testcases are new".

**Comment by jakkdu** [comment]
Thanks.
I haven't run QSYM with ASAN.
Normally, I compiled two binaries,
one for QSYM (without ASAN) and one for AFL (with ASAN)
and run two binaries with different command line.

Maybe I think it's better to note this one in the README.md.

**Comment by mxmssh** [comment]
Ok, it solves the problem, thank you.
