### ISSUE TITLE
Do not instrument shared libraries

### ISSUE THREAD

**Issue by lzina** [sslab-gatech/qsym#50]
Hi,
I am trying to trace only my target binary and ignore all shared libraries.
I found an option of `filter_no_shared_libs ` that should be send to the pin tool, but it does not work for me.

`'~/PycharmProjects/Qsym/venv/lib/python2.7/site-packages/qsym/../../../../third_party/pin-2.14-71313-gcc.4.4.7-linux/pin.sh' -ifeellucky -t '~/PycharmProjects/Qsym/venv/lib/python2.7/site-packages/qsym/pintool/obj-intel64/libqsym.so'  -filter_no_shared_libs  -logfile /tmp/tmpLlMTku/qsym-out-0/pin.log -i ~/PycharmProjects/Qsym/Tests/afl-output/qsym/.cur_input -s '1' -o '/tmp/tmpLlMTku/qsym-out-0' -help  -l  '1' -b '~/PycharmProjects/Qsym/Tests/afl-output/qsym/bitmap'  -- '~/PycharmProjects/Qsym/Tests/test_null_pointer.out'`

Please your help.
Thanks.

**Comment by jakkdu** [comment]
I have never tried to filter out all shared libraries.
Maybe you can selectively add instrumentation based on your binary in [here](https://github.com/sslab-gatech/qsym/blob/e67839e74a8d6960efb735d6e7dfdb58d634f2a0/qsym/pintool/third_party/libdft/api.cpp#L124)?

**Comment by insuyun** [comment]
Please re-open it if you need any more help.
