### ISSUE TITLE
Qsym+afl -> afl gets stuck  

### ISSUE THREAD

**Issue by lzina** [sslab-gatech/qsym#51]
Hi, 
When running AFL (only master or with a slave), everything works well. However, after starting Qsym on AFL test-cases, it gets stuck after a while (between minutes to half an hour)

I am running the tasks on a server with 122 GB RAM available.

Any guesses why it happens?
Thanks!

**Comment by jakkdu** [comment]
Could you give me your command line? and more elaborate your situation?

**Comment by insuyun** [comment]
Please re-open it if you need any more help.
