### ISSUE TITLE
Question in createDistinct function

### ISSUE THREAD

**Issue by sgzeng** [sslab-gatech/qsym#53]
In function at ExprRef SymbolicExprBuilder::createDistinct(ExprRef l, ExprRef r) at 
https://github.com/sslab-gatech/qsym/blob/master/qsym/pintool/codegen/expr_builder.cpp#L1081

Would it be better if:
```
ExprRef SymbolicExprBuilder::createDistinct(ExprRef l, ExprRef r) {
-  return createLNot(createEqual(l, r));
+  if (l == r)
+    return createTrue();
+  return ExprBuilder::createDistinct(l, r);
}
```

**Comment by jakkdu** [comment]
Hi!
I think if you want to add that, it should be createFalse(), not createTrue(). But, createEqual() has that check https://github.com/sslab-gatech/qsym/blob/master/qsym/pintool/codegen/expr_builder.cpp#L1074, and if the value is ConstantFoldingExprBuilder will make it as false https://github.com/sslab-gatech/qsym/blob/master/qsym/pintool/codegen/expr_builder.cpp#L620.
So I think there will not be that much difference.

**Comment by sgzeng** [comment]
Thanks so much for your explanation!
