### ISSUE TITLE
How to run QSYM against CGC binary

### ISSUE THREAD

**Issue by CvvT** [sslab-gatech/qsym#54]
Hi there,
Thanks for providing such an amazing tool. I tried QSYM recently against CGC binaries, but got the following error: E Unable to load ***/obj-ia32/libqsym.so.  Check the architecture type.

I used driller-afl to fuzz those binaries. I noticed that in the QSYM's paper CGC binaries were also evaluated with QSYM. I wonder how can I achieve it?

Thanks,
Weiteng

**Comment by jakkdu** [comment]
Hi. 
Since QSYM only supports ELF binary, we used a simple wrapper for cgc (https://github.com/jakkdu/libcgc-x86) to make a CGC binary into ELF format.
After running them, we used the common shellphish-afl for QSYM and driller to measure code coverage.

**Comment by CvvT** [comment]
Awesome! Thanks for your swift reply.
