### ISSUE TITLE
Missing Python packages?

### ISSUE THREAD

**Issue by Ayrx** [sslab-gatech/qsym#6]
I followed the install instructions:

```
; disable ptrace_scope for PIN
$ echo 0|sudo tee /proc/sys/kernel/yama/ptrace_scope

; install z3 and system deps
$ ./setup.sh

; install using virtual env
$ virtualenv venv
$ source venv/bin/activate
$ pip install .
```

and tried running the tests

```
$ cd tests
$ python build.py
$ python -m pytest -n $(nproc)
```

It seems like I also need to `pip install python-afl`  and something else that provides `from executor import Executor`  to resolve dependency errors when running the tests?

I can't figure out which package I need to install to resolve the `from executor import Executor` error.

**Comment by jakkdu** [comment]
Could you check whether qsym package is properly installed?
`from executor import Executor` gets `Executor` class from `executor.py`.
Moreover, qsym does not require python-afl.

**Comment by Ayrx** [comment]
Thanks! I'm not sure what happened the first time but I blew away the venv and started from scratch and all tests pass :)
