### ISSUE TITLE
Docker build fails because of Python dependency

### ISSUE THREAD

**Issue by sebastianpoeplau** [sslab-gatech/qsym#63]
Building a container with the supplied `Dockerfile` now fails because some Python dependency dropped support for Python 2 (and the versions are not pinned). As a workaround, I removed the dependency `pytest-xdist` from `setup.py`; then the container builds fine but obviously may not be capable of running the tests.

**Comment by jakkdu** [comment]
Thanks. I should support python3 as noted in https://github.com/sslab-gatech/qsym/issues/60.

**Comment by bjchan9an** [comment]
We also failed to build the docker due to the installation of ``pytest-xdist``. We modify the ``setup.sh`` to install pip with ``get-pip.py`` instead of ``apt-get``(https://github.com/sslab-gatech/qsym/pull/77). This makes us install a new version of pip and successfully build the docker.

**Comment by insuyun** [comment]
#79 resolve this issues.
