### ISSUE TITLE
Install Qsym on Ubuntu 18

### ISSUE THREAD

**Issue by lzina** [sslab-gatech/qsym#64]
Hi,
I will be glad to know if you are going to upload a version that supports Qsym in Ubuntu 18 in the near future.

Thanks

**Comment by jakkdu** [comment]
Sorry, but not near future.  I am too busy with other projects. My first priority is to make QSYM work with python3, and I can work for the latest Ubuntu.

**Comment by insuyun** [comment]
This is same with #4.
