### ISSUE TITLE
QSym clean installation for ubuntu 16.04 and 18.04

### ISSUE THREAD

**Issue by cryptomadco** [sslab-gatech/qsym#65]
Hey !

I just tried many times to install and use QSym (This awesome piece of work!), but unless using Vagrant thing, I just failed all times !

I'm working on a new fuzzer stuff and Qsym would be part of it's Concolic execution engine, so I want to integrate this into my fuzzer, but unfortunately, I didn't find a clean way to install QSym on my 16.04 box .

I would really appreciate you guys to make this possible, even QSym on a vmware box or virtualbox would be awesome .

QSym is one of the best things ever developed in the world of fuzzers / concolic execution engines, so it's need more attention ;-) . 

Thanks!
Regards.

**Comment by jakkdu** [comment]
Hi. Thank you for your attention.
Could you explain your errors more?
That would help me to understand your error.

Actually, the vagrant is just a wrapper.
It uses existing VMs as its underlying techniques.
So current our QSYM box uses virtualbox
and you can think of a vagrant as a just a script to setup the virtualbox VM.

Thank you.
Best,
Insu Yun

**Comment by insuyun** [comment]
Please re-open it if you need any more help.
