### ISSUE TITLE
How to support 32bit binary?

### ISSUE THREAD

**Issue by tinywhite321** [sslab-gatech/qsym#67]
Hi,

I would like to ask whether there is a way to support 32 bit binary or is it already well-supported?

**Comment by jakkdu** [comment]
I tried for a small set of binaries, it works.
This patch makes us to support 32-bit more smoothly (https://github.com/sslab-gatech/qsym/pull/27). 
If you have any trouble, let me know.
Thank you.

Best,
Insu Yun.

**Comment by tinywhite321** [comment]
Thank you for your response!

I think it can handle most of my use cases.

Qsym is great, is there any future plan to upgrade for the newest kernel with Pin 3?

**Comment by jakkdu** [comment]
Hope so. But it's not an easy job.
I took a look PIN3 and it's really hard to use as shown in https://github.com/google/fuzzbench/issues/131.
If I have spare time, I would like to work on.
Thank you.

Best,
Insu Yun.

**Comment by tinywhite321** [comment]
Got it.
I am looking forward to any update news.
Thank you so much.

Best regards,
