### ISSUE TITLE
Beginner: error occurs when run for testing

### ISSUE THREAD

**Issue by CK213** [sslab-gatech/qsym#69]
Hi,

I am a beginner of using QSYM, I have been following the instruction in "Run for testing" mentioned in the ReadMe. However, `No module named pytest`error occurred when I run `python -m pytest -n $(nproc)`

Here is what it showed on my terminal:
`~/Desktop/qsym/tests$ python build.py`
`~/Desktop/qsym/tests$ python -m pytest -n $(nproc)`
**`/usr/bin/python: No module named pytest`**

Did I miss anything? and how can I fix it?

Thanks in advance.

**Comment by Fernandes1198** [comment]
Hi,

Can you please tell me how did you fix this issue? 

Thanks in advance
Best Regards
