### ISSUE TITLE
Null-deref on DependencyForest::addNode

### ISSUE THREAD

**Issue by tunz** [sslab-gatech/qsym#7]
When `node->getDependencies()` returns an empty set, the loop is not executed, so the `tree` is also not updated. Thus, it directly accesses `tree`, which is initialized to null pointer, after the loop. I'm not sure if we can just add a nullptr check here or the dependency set should not be empty. In my case, the node is a ConstantExpr, so it does not have any child.

https://github.com/sslab-gatech/qsym/blob/b063dbbd35bc58551a895b7f454fb621192d9c82/qsym/pintool/dependency.h#L68-L71
https://github.com/sslab-gatech/qsym/blob/b063dbbd35bc58551a895b7f454fb621192d9c82/qsym/pintool/dependency.h#L82-L83

I'm using this temporary fix to avoid crashes.
```diff
diff --git a/qsym/pintool/dependency.h b/qsym/pintool/dependency.h
index 0a1d185..2f3594e 100644
--- a/qsym/pintool/dependency.h
+++ b/qsym/pintool/dependency.h
@@ -80,7 +80,8 @@ namespace qsym {
           }
           forest_[index] = tree;
         }
-        tree->addNode(node);
+        if (tree != nullptr)
+          tree->addNode(node);
       }
 
     private:
```

**Comment by jakkdu** [comment]
Do you have a program and input that triggers the crash?
Let me debug this. The tree should not be NULL in a normal case.

**Comment by tunz** [comment]
I've reproduced it as a toy program.

*test.c*
```c
#include <stdio.h>

int *asm_fn();

int main(int argc, char **argv) {
  const int v1 = 0x78;
  const int v2 = 0x12345678;
  FILE *fp;
  int i;
  int num;
  fp = fopen(argv[1], "r");
  fread(&num, sizeof(num), 1, fp);

  for (i = 0; i < 300; i++) {
    if (v1 - num != v2)
      asm_fn();
  }

  fclose(fp);
}
```
*asm.as*
```asm
.section .text
.globl asm_fn
.type asm_fn, @function
asm_fn:
jz next
next:
ret
```

Compile with this following command, and execute it. I've tested it in Ubuntu 16.04.4 64bit.
```
$ as asm.s -o asm.o; gcc -c test.c -o test.o; gcc asm.o test.o -o ./a.out
$ echo -ne "\x00\x00\x00\x00" > empty
$ ./a.out ./empty
```

seems like it prunes the *asm_fn* basic block because of repetitive visits, and the pruned evaluated expression is passed to the *addNode* when the first instruction of the BB is *jcc*.

**Comment by jakkdu** [comment]
Thanks. It looks like very minimal test case.
I will dig into it tomorrow!
