### ISSUE TITLE
Does QSYM sync bitmap with master/slave fuzzer?

### ISSUE THREAD

**Issue by Alkaid-Benetnash** [sslab-gatech/qsym#71]
I wonder whether QSYM syncs the bitmap with the other AFL fuzzer instances.
According to the code, I believe the bitmap is the key to define "interesting" new paths, but cannot find how does QSYM avoid exploring paths already covered by AFL.

For instance, I find the [pintool Executor](https://github.com/sslab-gatech/qsym/blob/master/qsym/afl.py#L223) and the [minimizer](https://github.com/sslab-gatech/qsym/blob/master/qsym/minimizer.py#L88) both maintains their own bitmap to define "what is interesting". But they seem never sync with each other, nor the other two AFL fuzzer instances.

Do I miss anything? If not, what is the rationale behind this decision? I thought avoiding generating testcases already covered by AFL should be important to QSYM.

**Comment by insuyun** [comment]
Hi, @Alkaid-Benetnash. I am very sorry. I missed this issue.
QSYM uses AFL's methods for synching bitmap.
Instead of syncing bitmap directly, it gets new inputs from each master and slave.
For more information, you can check https://volatileminds.net/2015/07/01/advanced-afl-usage.html.

Thank you.
