### ISSUE TITLE
Incorrect handling for brk

### ISSUE THREAD

**Issue by yiyuaner** [sslab-gatech/qsym#72]
From Linux's documentation:
```
int brk(void *addr)
// brk() sets the program break to the value specified by addr and
// returns 0 on success, -1 on error.
```
However, in the function [`postBrkHook`](https://github.com/sslab-gatech/qsym/blob/master/qsym/pintool/third_party/libdft/syscall_desc.cpp#L498) :
```
// __NR_brk post syscall hook
static void
postBrkHook(SyscallContext *ctx)
{
	// brk() return value; in Linux brk returns
	// the address of the new program break, or
	// the current value in case of failure
	ADDRINT addr = ctx->ret;

  if (unlikely(addr == g_memory.brk_end()))
    return;

  LOG_DEBUG("brk(" + hexstr(g_memory.brk_start()) + "-" + hexstr(addr) + ")\n");
  g_memory.brk(addr);
}
```
It seems to use the return value of `brk` (`addr = ctx->ret`, **which is either 0 or -1**) as the the address for the program break, while the actual program break should be set to the argument of `brk`.

Is this a problem or I have missed out something here? Hope for your help!

**Comment by insuyun** [comment]
Thank you for letting us know.
I think you are correct.
It needs to be fixed.
