### ISSUE TITLE
Qsym stalls after several hours with "Sleep for getting files"

### ISSUE THREAD

**Issue by novafacing** [sslab-gatech/qsym#73]
I'm attempting to fuzz several binaries using Qsym+AFL, and I am encountering very strange behavior. After 2-3 hours of fuzzing, both the main and secondary instance of AFL stall, and I get a continuous log from qsym of, and no more test cases are executed:

```
DEBUG:qsym.afl:Sleep for getting files
DEBUG:qsym.afl:Sleep for getting files
...
```

My environment is as follows:

OS: Ubuntu 16.04.7 LTS
Kernel: 4.4.0-186-generic x86_64
Commands to run Qsym:

Main AFL Instance: 
`AFL_SKIP_BIN_CHECK=1 SEEDRECORD=200 AFL_SKIP_CRASHES=1 AFL_NO_AFFINITY=1 $AFL_ROOT/afl-fuzz -Q -M afl-main -i $CORPUS -o $OUTPUTS -- $AFL_CMDLINE`

Secondary AFL Instance:
`AFL_SKIP_BIN_CHECK=1 SEEDRECORD=200 AFL_SKIP_CRASHES=1 AFL_NO_AFFINITY=1 $AFL_ROOT/afl-fuzz -Q -S afl-secondary -i $CORPUS -o $OUTPUTS -- $AFL_CMDLINE`

Qsym Instance:
`python bin/run_qsym_afl.py -a afl-secondary -o $OUTPUTS -n qsym -- $AFL_CMDLINE`

In this case, `AFL_CMDLINE=./axtls/axtls s_server -accept 15001 -pass abcd -cert @@`

I installed qsym exactly as recommended in README.md, and all test cases pass when running pytest.

Any assistance with this would be awesome! I am trying to do a 24-hour fuzzing run, so having the fuzzer stop after 2-3 hours is a bit less than ideal.

Thanks!

**Comment by insuyun** [comment]
Hi. QSYM depends on AFL for getting new files.
Unfortunately, if AFL stalls finding new test cases, QSYM will stall.
I think one way to resolve this to run QSYM on-demand.
But it is not how the current QSYM works. 

I think you can also check https://github.com/eurecom-s3/symqemu,
which is quiet recent work for hybrid fuzzing.
(I also haven't check it but only its paper though).

Also if you are trying to fuzz well-structured format (like certificates),
I think hybrid fuzzing might not be ideal.
It is limited to handling complex syntax structures like certificates.
You may also can check certificate-specific fuzzers.

Hope this help you.
Best,
Insu Yun

**Comment by novafacing** [comment]
This is a very helpful answer, thanks. My initial assumption was that AFL got test cases from Qsym instead of the other way around, this makes quite a bit more sense. I'll take a look at your suggestions!
