### ISSUE TITLE
Vagrant tutorial fails with example.c

### ISSUE THREAD

**Issue by rmallof** [sslab-gatech/qsym#74]
Hi,

thank you for releasing the code for the project, it's pretty interesting!

I'm following the steps at https://github.com/sslab-gatech/qsym/tree/master/vagrant but eventually I find the following error:

vagrant@ubuntu-xenial:~$ ./qsym/bin/run_qsym.py -i input/input-0 -o tests -- ./example @@
Traceback (most recent call last):
  File "./qsym/bin/run_qsym.py", line 4, in <module>
    from qsym import Executor, utils
ImportError: No module named qsym

Am I missing something or maybe something is out-of-date?

Thanks in advance

**Comment by yiyunliu** [comment]
I got the same issue. By checking the log during provision, it looks like the following step which was supposed to install qsym failed: https://github.com/sslab-gatech/qsym/blob/4fa4363cd09d40a422efa24d359b87f849202d4a/vagrant/Vagrantfile#L35

**Comment by yiyunliu** [comment]
The issue is the exact same as the one mentioned in #63. After removing `pytest-xdist` from `setup.py` I was able to install without any issues.

**Comment by insuyun** [comment]
#77 and #79 resolve this issue.
