### ISSUE TITLE
get the error when I pip install . in venv

### ISSUE THREAD

**Issue by noobLei** [sslab-gatech/qsym#76]
![M7N5F8@PR6UIO5H710C$XA3](https://user-images.githubusercontent.com/71857725/132112325-e81be633-4c84-4be7-883e-f18a242d22eb.png)

**Comment by insuyun** [comment]
Sorry but it is difficult to understand your issue only with this error. Do you have a full list of it?

**Comment by insuyun** [comment]
Please re-open it if you need any more help.

**Comment by 001SM** [comment]
我也遇到了这个问题，希望能快点解决
