### ISSUE TITLE
get the error when I docker build -t qsym ./

### ISSUE THREAD

**Issue by Ricardio609** [sslab-gatech/qsym#78]
![image](https://user-images.githubusercontent.com/64991294/142725383-1a5a27eb-d89c-4393-8116-54f78a913a76.png)
![image](https://user-images.githubusercontent.com/64991294/142725398-bae4d785-0a14-4cd8-9e59-806f3c260892.png)

**Comment by insuyun** [comment]
Hi, Ricradio.
Sounds strange to me.
Because we installed pip in https://github.com/sslab-gatech/qsym/blob/master/setup.sh#L21.

Let me check this issue this week again.
Thank you for reporting.

**Comment by Ricardio609** [comment]
HI, Insuyun.
I succeed by using docker and a little change. I changed  wget https://bootstrap.pypa.io/get-pip.py to wget https://bootstrap.pypa.io/pip/2.7/get-pip.py in https://github.com/sslab-gatech/qsym/blob/master/setup.sh#L20. Maybe it python dependency ?

**Comment by insuyun** [comment]
Oh. Thank you for letting me know.
I think that's the reason because we built this before python2.7 is deprecated.
Do you want to make pull request?
Otherwise, I can update.

**Comment by Ricardio609** [comment]
ok, I have made a pull request. Thank you suggestion.

**Comment by insuyun** [comment]
Thank you!
