### ISSUE TITLE
qsym.afl:Cannot find pintool. Maybe updating?

### ISSUE THREAD

**Issue by bboysteed** [sslab-gatech/qsym#80]
$ bin/run_qsym_afl.py -a afl-slave -o $OUTPUT -n qsym -- $QSYM_CMDLINE
DEBUG:qsym.afl:Temp directory=/tmp/tmpN065dk
DEBUG:qsym.afl:Cannot find pintool. Maybe updating?

**Comment by insuyun** [comment]
Hi, @bboysteed . It haapens when qsym cannot find pintool.
Could you elaborate your situation more?

**Comment by insuyun** [comment]
Please re-open it if you need any more help.
