### ISSUE TITLE
error: execute ./setup.sh in Ubuntu16

### ISSUE THREAD

**Issue by Ricardio609** [sslab-gatech/qsym#81]
![image](https://user-images.githubusercontent.com/64991294/145710948-20a5ca1f-b561-4576-a1aa-cbdac905e3ec.png)
![image](https://user-images.githubusercontent.com/64991294/145710977-ab4c8f85-c47c-47f0-b995-4fbbd4df8f23.png)
![image](https://user-images.githubusercontent.com/64991294/145710985-d3474154-1398-4ca8-8ee7-a4e65e7c3ca5.png)
![image](https://user-images.githubusercontent.com/64991294/145711001-72c5db04-8459-4c7e-bc99-f61636436efa.png)

My env is Ubuntu18.  could I solve the error ? thaks!

**Comment by insuyun** [comment]
Hi, Ricardo. Could you use Docker for install?

**Comment by Ricardio609** [comment]
Hi, insuyun. I have successed in docker,but I need to directely install it. Now Z3 not installed.
![image](https://user-images.githubusercontent.com/64991294/145712093-60ddb248-ef33-4f58-aad5-40cc227e788f.png)
Have you encountered this error  ?

**Comment by 001SM** [comment]
我也遇到了这个问题，希望能快点出现解决方案

**Comment by insuyun** [comment]
Hi, @Ricardio609. Could you let me know how you resolve this issue?

**Comment by Ricardio609** [comment]
> Hi, @Ricardio609. Could you let me know how you resolve this issue?

Hi, insuyun. I successed installed in vagrant , docker and ubuntu16. But it failed in ubuntu20, maybe kernel denpency.

**Comment by 001SM** [comment]
> 你好，@Ricardio609.你能告诉我你是如何解决这个问题的吗？

Sorry, I can't solve this problem

**Comment by Ricardio609** [comment]
> > 你好，@Ricardio609.你能告诉我你是如何解决这个问题的吗？
> 
> Sorry, I can't solve this problem

It successful  installed  after changing the installation environment. for example using docker or vagrant.
