### ISSUE TITLE
How to change the number of the additional constraints when using Optimistic Solving?

### ISSUE THREAD

**Issue by MoonBirdLin** [sslab-gatech/qsym#84]
Hi, Nice Project.
I'm a student interested in this good design. I want to compare the performance with different numbers of the additional constraints; but I haven't found the interface to change it. Could you tell me how to set this parameter in sourcecode, or other method to change it?  By the way , if you don't mind , can you tell me your OS and software experiment environment when you fuzz on the LAVA-M database, because my experimental results were lower than expected.
Thanks.

**Comment by MoonBirdLin** [comment]
> Hi, Nice Project. I'm a student interested in this good design. I want to compare the performance with different numbers of the additional constraints; but I haven't found the interface to change it. Could you tell me how to set this parameter in sourcecode, or other method to change it? By the way , if you don't mind , can you tell me your OS and software experiment environment when you fuzz on the LAVA-M database, because my experimental results were lower than expected. Thanks.

Especially on the LAVA-M-who program, I can only find 2 unique crashes after running 6 hours.

I used install-lava.sh in /vagrant/LAVA/ to install LAVA-M database and used following command to run afl and qsym:
export FUZZ_LIB=~/QSYM/lava_corpus/LAVA-M/who/coreutils-8.24-lava-safe/ 
export FUZZED_BINARY=lava-install/bin/who
export FUZZED_OPT=
**And Run Following Commands in Three Different Terminals**
afl-fuzz -M afl-master -m none -i $FUZZ_LIB/afl-input -o $FUZZ_LIB/afl-output -- $FUZZ_LIB/$FUZZED_BINARY $FUZZED_OPT @@ 
afl-fuzz -S afl-slave -m none -i $FUZZ_LIB/afl-input -o $FUZZ_LIB/afl-output -- $FUZZ_LIB/$FUZZED_BINARY $FUZZED_OPT @@
python ../bin/run_qsym_afl.py -a afl-slave -o $FUZZ_LIB/afl-output -n qsym -- $FUZZ_LIB/afl-$FUZZED_BINARY

Maybe there is some wrong with my usage, can you help me? Thanks.

**Comment by insuyun** [comment]
Hi, MoonBirdLin.

1. https://github.com/sslab-gatech/qsym/blob/4fa4363cd09d40a422efa24d359b87f849202d4a/qsym/pintool/solver.cpp#L526

This is a part of optimistic solving. Unfortunately, we don't have a good API for changing the number of constraints. Maybe you can modify code to add more constraints instead of the last one at that point.

2. We have used Ubuntu 16.04 for our evaluation. We have provided VM script for QSYM. Maybe you can check this https://github.com/sslab-gatech/qsym/tree/master/vagrant.

**Comment by MoonBirdLin** [comment]
Thans for help. I will try to change  the number of constraints by modifying the code.
